import React,{createContext,useContext,useEffect,useMemo,useState}from"react";
export type Language="en"|"pt"|"es";
const DICT:Record<Language,Record<string,string>>={
 en:{
  "nav.room":"Room","nav.games":"Games","nav.agency":"Agency","nav.admin":"Admin","auth.login":"Log in","auth.signup":"Create account","auth.logout":"Log out","auth.name":"Name","auth.email":"Email","auth.password":"Password","auth.wait":"Please wait…","auth.switchSignup":"Create account","auth.switchLogin":"I already have an account","auth.test":"Test mode: room, 30 seats, chat and games can run without the backend.",
  "room.live":"LIVE ROOM","room.positions":"configured seats • voice • optional video • chat • gifts","room.refresh":"Refresh","room.video":"Video","room.chat":"Chat","room.gift":"Gift","room.seats":"Seats","room.join":"Join room","room.leave":"Leave seat","room.micOn":"Turn microphone on","room.micOff":"Turn microphone off","room.loginRequired":"Log in and become an active member to take a seat.","room.occupied":"occupied","room.free":"free","room.connecting":"Connecting voice…","room.chatTitle":"Room chat","room.realtime":"Realtime","chat.placeholder":"Write a message…","chat.loginPlaceholder":"Log in to send","chat.send":"Send","chat.translate":"Translate","chat.translated":"Translated",
  "games.title":"Room games","games.count":"20 games • free + virtual credits","games.free":"Free","games.virtual":"Virtual credits","games.back":"← Back to games","games.balance":"Balance","games.wager":"Wager","games.play":"Play round","slots.title":"Slots","slots.count":"20 slots • all enabled for virtual testing","slots.back":"← Back to slots","slots.spin":"SPIN","slots.rocket":"🚀 Launch rocket","slots.target":"Target","slots.height":"Height","slots.hint":"Free mode does not change balance. Credit mode uses only the virtual test wallet.",
  "wallet.virtual":"virtual test credits","status.livekit":"LIVEKIT • VOICE CONNECTED","status.configured":"LIVEKIT CONFIGURED","status.pending":"VOICE PENDING • LIVEKIT NOT CONFIGURED","language":"Language","translation.target":"Translate to"
 },
 pt:{
  "nav.room":"Sala","nav.games":"Jogos","nav.agency":"Agência","nav.admin":"ADM","auth.login":"Entrar","auth.signup":"Criar conta","auth.logout":"Sair","auth.name":"Nome","auth.email":"E-mail","auth.password":"Senha","auth.wait":"Aguarde…","auth.switchSignup":"Criar conta","auth.switchLogin":"Já tenho conta","auth.test":"Modo teste: sala, 30 cadeiras, chat e jogos podem ser usados sem backend.",
  "room.live":"SALA AO VIVO","room.positions":"posições configuradas • voz • vídeo opcional • chat • presentes","room.refresh":"Atualizar","room.video":"Vídeo","room.chat":"Chat","room.gift":"Presentear","room.seats":"Cadeirinhas","room.join":"Entrar na sala","room.leave":"Sair da cadeira","room.micOn":"Ligar microfone","room.micOff":"Desligar microfone","room.loginRequired":"Login e membro ativo são necessários para ocupar uma cadeira.","room.occupied":"ocupada","room.free":"livre","room.connecting":"Conectando voz…","room.chatTitle":"Chat da sala","room.realtime":"Tempo real","chat.placeholder":"Digite uma mensagem…","chat.loginPlaceholder":"Login necessário para enviar","chat.send":"Enviar","chat.translate":"Traduzir","chat.translated":"Traduzido",
  "games.title":"Jogos de sala","games.count":"20 jogos • grátis + créditos virtuais","games.free":"Grátis","games.virtual":"Com créditos","games.back":"← Voltar aos jogos","games.balance":"Saldo","games.wager":"Aposta","games.play":"Jogar rodada","slots.title":"Slots","slots.count":"20 slots • todos ativos para teste virtual","slots.back":"← Voltar aos slots","slots.spin":"GIRAR","slots.rocket":"🚀 Subir foguete","slots.target":"Meta","slots.height":"Altura","slots.hint":"Grátis não altera saldo. O modo com créditos usa somente a carteira virtual de teste.",
  "wallet.virtual":"créditos virtuais de teste","status.livekit":"LIVEKIT • VOZ CONECTADA","status.configured":"LIVEKIT CONFIGURADO","status.pending":"VOZ PENDENTE • LIVEKIT NÃO CONFIGURADO","language":"Idioma","translation.target":"Traduzir para"
 },
 es:{
  "nav.room":"Sala","nav.games":"Juegos","nav.agency":"Agencia","nav.admin":"ADM","auth.login":"Iniciar sesión","auth.signup":"Crear cuenta","auth.logout":"Salir","auth.name":"Nombre","auth.email":"Correo","auth.password":"Contraseña","auth.wait":"Espere…","auth.switchSignup":"Crear cuenta","auth.switchLogin":"Ya tengo cuenta","auth.test":"Modo de prueba: sala, 30 asientos, chat y juegos pueden usarse sin backend.",
  "room.live":"SALA EN VIVO","room.positions":"posiciones configuradas • voz • vídeo opcional • chat • regalos","room.refresh":"Actualizar","room.video":"Vídeo","room.chat":"Chat","room.gift":"Regalar","room.seats":"Asientos","room.join":"Entrar a la sala","room.leave":"Salir del asiento","room.micOn":"Activar micrófono","room.micOff":"Desactivar micrófono","room.loginRequired":"Se necesita iniciar sesión y ser miembro activo para ocupar un asiento.","room.occupied":"ocupado","room.free":"libre","room.connecting":"Conectando voz…","room.chatTitle":"Chat de la sala","room.realtime":"Tiempo real","chat.placeholder":"Escribe un mensaje…","chat.loginPlaceholder":"Inicia sesión para enviar","chat.send":"Enviar","chat.translate":"Traducir","chat.translated":"Traducido",
  "games.title":"Juegos de sala","games.count":"20 juegos • gratis + créditos virtuales","games.free":"Gratis","games.virtual":"Créditos virtuales","games.back":"← Volver a los juegos","games.balance":"Saldo","games.wager":"Apuesta","games.play":"Jugar ronda","slots.title":"Slots","slots.count":"20 slots • todos activos para pruebas virtuales","slots.back":"← Volver a los slots","slots.spin":"GIRAR","slots.rocket":"🚀 Lanzar cohete","slots.target":"Meta","slots.height":"Altura","slots.hint":"El modo gratis no cambia el saldo. El modo con créditos usa solo la billetera virtual de prueba.",
  "wallet.virtual":"créditos virtuales de prueba","status.livekit":"LIVEKIT • VOZ CONECTADA","status.configured":"LIVEKIT CONFIGURADO","status.pending":"VOZ PENDIENTE • LIVEKIT NO CONFIGURADO","language":"Idioma","translation.target":"Traducir a"
 }
};
const LANGUAGE_KEY="estrela_language";
type Ctx={language:Language;setLanguage:(l:Language)=>void;t:(key:string)=>string};
const I18nContext=createContext<Ctx|null>(null);
export function I18nProvider({children}:{children:React.ReactNode}){
 const [language,setLanguageState]=useState<Language>(()=>{const v=localStorage.getItem(LANGUAGE_KEY);return v==="pt"||v==="es"||v==="en"?v:"en"});
 const setLanguage=(l:Language)=>{setLanguageState(l);localStorage.setItem(LANGUAGE_KEY,l);window.dispatchEvent(new CustomEvent("estrela-language",{detail:l}))};
 useEffect(()=>{const h=(e:Event)=>{const l=(e as CustomEvent).detail;if(l==="en"||l==="pt"||l==="es")setLanguageState(l)};window.addEventListener("estrela-language",h);return()=>window.removeEventListener("estrela-language",h)},[]);
 const value=useMemo(()=>({language,setLanguage,t:(key:string)=>DICT[language][key]??DICT.en[key]??key}),[language]);
 return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(){const v=useContext(I18nContext);if(!v)throw new Error("I18nProvider ausente");return v}
export const GAME_NAMES:Record<string,Record<Language,string>>={
 STAR_01:{en:"Cosmic Star",pt:"Estrela Cósmica",es:"Estrella Cósmica"},STAR_02:{en:"Golden Orbit",pt:"Órbita Dourada",es:"Órbita Dorada"},STAR_03:{en:"Violet Moon",pt:"Lua Violeta",es:"Luna Violeta"},STAR_04:{en:"Nebula",pt:"Nebulosa",es:"Nebulosa"},STAR_05:{en:"Supernova",pt:"Supernova",es:"Supernova"},STAR_06:{en:"Comet",pt:"Cometa",es:"Cometa"},STAR_07:{en:"Galaxy",pt:"Galáxia",es:"Galaxia"},STAR_08:{en:"Black Hole",pt:"Buraco Negro",es:"Agujero Negro"},STAR_09:{en:"Constellation",pt:"Constelação",es:"Constelación"},STAR_10:{en:"Star Treasure",pt:"Tesouro Estelar",es:"Tesoro Estelar"},STAR_11:{en:"Cosmic Zeus",pt:"Zeus Cósmico",es:"Zeus Cósmico"},STAR_12:{en:"Cosmic Cleopatra",pt:"Cleópatra Cósmica",es:"Cleopatra Cósmica"},STAR_13:{en:"Star Ice",pt:"Gelo Estelar",es:"Hielo Estelar"},STAR_14:{en:"Rocket",pt:"Foguete",es:"Cohete"},STAR_15:{en:"Lucky Egg",pt:"Ovo da Sorte",es:"Huevo de la Suerte"},STAR_16:{en:"Cosmic Train",pt:"Trem Cósmico",es:"Tren Cósmico"},STAR_17:{en:"Star Hunter",pt:"Caçador Estelar",es:"Cazador Estelar"},STAR_18:{en:"Cosmic Cream",pt:"Creme Cósmico",es:"Crema Cósmica"},STAR_19:{en:"Star Yumi",pt:"Yumi Estelar",es:"Yumi Estelar"},STAR_20:{en:"Star Bean",pt:"Feijão Estelar",es:"Frijol Estelar"}
};
export const SOCIAL_NAMES:Record<string,Record<Language,string>>={
 tic_tac_toe:{en:"Tic-Tac-Toe",pt:"Três em Linha",es:"Tres en Raya"},memory:{en:"Star Memory",pt:"Memória Estelar",es:"Memoria Estelar"},reaction:{en:"Cosmic Reflex",pt:"Reflexo Cósmico",es:"Reflejo Cósmico"},sequence:{en:"Star Sequence",pt:"Sequência Estelar",es:"Secuencia Estelar"},math:{en:"Math Challenge",pt:"Desafio Matemático",es:"Desafío Matemático"},rps:{en:"Rock Paper Scissors",pt:"Pedra Papel Tesoura",es:"Piedra Papel Tijera"},word_scramble:{en:"Word Scramble",pt:"Palavra Embaralhada",es:"Palabra Revuelta"},color_match:{en:"Cosmic Colors",pt:"Cores Cósmicas",es:"Colores Cósmicos"},tap_count:{en:"Star Tap Count",pt:"Contador Estelar",es:"Contador Estelar"},pattern:{en:"Galactic Pattern",pt:"Padrão Galáctico",es:"Patrón Galáctico"},anagram:{en:"Anagram",pt:"Anagrama",es:"Anagrama"},quiz:{en:"Cosmic Quiz",pt:"Quiz Cósmico",es:"Quiz Cósmico"},simon:{en:"Stars in Order",pt:"Estrelas em Ordem",es:"Estrellas en Orden"},grid:{en:"Lightning Grid",pt:"Grade Relâmpago",es:"Cuadrícula Relámpago"},odd_one:{en:"Constellation Odd One",pt:"Intruso na Constelação",es:"Intruso en la Constelación"},word_chain:{en:"Word Chain",pt:"Cadeia de Palavras",es:"Cadena de Palabras"},logic:{en:"Star Logic",pt:"Lógica Estelar",es:"Lógica Estelar"},count_stars:{en:"Count the Stars",pt:"Conte as Estrelas",es:"Cuenta las Estrellas"},typing:{en:"Cosmic Typing",pt:"Digitação Cósmica",es:"Escritura Cósmica"},color_memory:{en:"Color Memory",pt:"Memória de Cores",es:"Memoria de Colores"}
};