import React,{useEffect,useMemo,useRef,useState}from"react";
import RoleHierarchy from"./components/RoleHierarchy";
import GameCenter from"./components/GameCenter";
import EventCalendar from"./components/EventCalendar";
import{Gift,Gamepad2,Shield,Users,Settings,Mic,Video,MessageCircle,Star,Crown,LogIn,LogOut,RefreshCw}from"lucide-react";
import{getLiveRoom,getCurrentMemberId,claimSeat,leaveSeat,listActiveSeats,subscribeToRoomSeats,RoomSession}from"./lib/room";
import{sendRoomMessage,subscribeToRoomChat}from"./lib/chat";
import{livekitConfigured,createLiveKitRoom,connectLiveKitRoom,enableMicrophone,enableCamera,subscribeLiveKitState,LiveKitMediaState}from"./lib/livekit";
import{getLiveKitToken}from"./lib/livekit-token";
import{supabase,supabaseConfigured}from"./lib/supabase";
import{signIn,signUp,signOut}from"./lib/auth";
import{listRoomGifts,getWalletBalance,transferVirtualGift}from"./lib/gifts";
import{diagnosticSnapshot}from"./lib/diagnostics";
import{Track,Room,RoomEvent}from"livekit-client";



function App(){
 const[tab,setTab]=useState("sala"),[room,setRoom]=useState<RoomSession|null>(null),[seats,setSeats]=useState<any[]>([]),[memberId,setMemberId]=useState<string|null>(null),[chat,setChat]=useState<any[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[authMode,setAuthMode]=useState<"login"|"signup">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[displayName,setDisplayName]=useState(""),[authBusy,setAuthBusy]=useState(false),[userEmail,setUserEmail]=useState<string|null>(null);
 const[gifts,setGifts]=useState<any[]>([]),[walletBalance,setWalletBalance]=useState(0),[giftOpen,setGiftOpen]=useState(false),[giftBusy,setGiftBusy]=useState(false);
 const[livekitState,setLivekitState]=useState<LiveKitMediaState|null>(null),[voiceBusy,setVoiceBusy]=useState(false),[voiceError,setVoiceError]=useState("");
 const livekitRoomRef=useRef<Room|null>(null),[callSessionId,setCallSessionId]=useState<string|null>(null);

 const load=async()=>{setLoading(true);setError("");try{if(!supabase){setRoom({id:"demo-room",room_key:"demo-room",title:"Estrela da Sorte — Modo Teste",status:"live",seats:30,video_enabled:true,chat_enabled:true});setMemberId("demo-user");setSeats([]);setChat([]);return}const live=await getLiveRoom();setRoom(live);diagnosticSnapshot("Sala carregada",live);if(live){const activeSeats=await listActiveSeats(live.id);setSeats(activeSeats);diagnosticSnapshot("Participantes da sala",activeSeats);setMemberId(await getCurrentMemberId());setGifts(await listRoomGifts());setWalletBalance(await getWalletBalance())}else{setSeats([]);setMemberId(null)}}catch(e:any){setError(e?.message||"Não foi possível consultar a sala.")}finally{setLoading(false)}};
 useEffect(()=>{void load();if(supabase){void supabase.auth.getSession().then(({data})=>setUserEmail(data.session?.user.email??null))}},[]);
 useEffect(()=>{if(!room||!supabase)return;const stopChat=subscribeToRoomChat(room.id,m=>{diagnosticSnapshot("Mensagem de chat recebida",m);setChat(v=>[...v,m])});const stopSeats=subscribeToRoomSeats(room.id,()=>{void listActiveSeats(room.id).then(setSeats).catch(e=>setError(e?.message||"Não foi possível atualizar as cadeiras."))});return()=>{stopChat();stopSeats()}},[room]);
 useEffect(()=>{if(!supabase)return;const{data}=supabase.auth.onAuthStateChange(()=>{void getCurrentMemberId().then(setMemberId).catch(()=>setMemberId(null))});return()=>data.subscription.unsubscribe()},[]);

 const occupied=new Map(seats.map(s=>[Number(s.seat_no),s])),mySeat=useMemo(()=>seats.find(s=>s.member_id===memberId)?.seat_no??null,[seats,memberId]);

 useEffect(()=>{let disposed=false;let stopState:undefined|(()=>void);let localCallId:string|null=null;const connectVoice=async()=>{if(disposed||!room||!memberId||!mySeat||!livekitConfigured||livekitRoomRef.current)return;setVoiceBusy(true);setVoiceError("");try{const auth=await supabase?.auth.getUser();const user=auth?.data.user;if(!user)throw new Error("Login necessário para conectar a voz");const authToken=await getLiveKitToken(room.room_key);const lk=createLiveKitRoom();livekitRoomRef.current=lk;stopState=subscribeLiveKitState(lk,setLivekitState);lk.on(RoomEvent.TrackSubscribed,(track)=>{if(track.kind===Track.Kind.Audio){const el=track.attach();el.autoplay=true;el.setAttribute("data-livekit-audio","true");document.body.appendChild(el)}});lk.on(RoomEvent.TrackUnsubscribed,(track)=>track.detach());await connectLiveKitRoom(lk,authToken.token,authToken.url??undefined);const{data:call,error:callError}=await supabase!.from("call_sessions").insert({room_id:room.id,call_type:"voice",livekit_room_name:room.room_key,started_by:user.id}).select("id").single();if(callError)throw callError;localCallId=call.id;setCallSessionId(call.id);diagnosticSnapshot("LiveKit conectado",{room:room.room_key,user:user.id});}catch(e:any){if(!disposed){setVoiceError(e?.message||"Não foi possível conectar a voz.");diagnosticSnapshot("Falha LiveKit",e?.message)}}finally{if(!disposed)setVoiceBusy(false)}};void connectVoice();return()=>{disposed=true;if(stopState)stopState();const lk=livekitRoomRef.current;livekitRoomRef.current=null;setLivekitState(null);if(lk){void lk.disconnect();lk.removeAllListeners()}if(localCallId&&supabase){void supabase.from("call_sessions").update({status:"ended",ended_at:new Date().toISOString()}).eq("id",localCallId);setCallSessionId(null)}}},[room,memberId,mySeat,livekitConfigured]);

 const join=async()=>{if(!room||!memberId)return;setBusy(true);setError("");try{if(!supabase){setSeats(v=>v.some(s=>s.member_id===memberId)?v:[...v,{id:"demo-seat",member_id:memberId,seat_no:v.length+1}]);return}await claimSeat(room.id,memberId);await load()}catch(e:any){setError(e?.message||"Não foi possível ocupar a cadeira.")}finally{setBusy(false)}};
 const leave=async()=>{if(!room||!memberId)return;setBusy(true);setError("");try{if(!supabase){setSeats(v=>v.filter(s=>s.member_id!==memberId));return}await leaveSeat(room.id,memberId);await load()}catch(e:any){setError(e?.message||"Não foi possível sair da cadeira.")}finally{setBusy(false)}};
 const toggleMic=async()=>{const lk=livekitRoomRef.current;if(!lk)return;setVoiceBusy(true);setVoiceError("");try{await enableMicrophone(lk,!lk.localParticipant.isMicrophoneEnabled)}catch(e:any){setVoiceError(e?.message||"Não foi possível alterar o microfone.")}finally{setVoiceBusy(false)}};
 const send=async()=>{if(!room||!message.trim())return;try{if(!supabase){setChat(v=>[...v,{id:crypto.randomUUID(),sender_user_id:"demo-user",body:message.trim()}]);setMessage("");return}await sendRoomMessage(room.id,message.trim());setMessage("")}catch(e:any){setError(e?.message||"Não foi possível enviar a mensagem.")}};
 const submitAuth=async()=>{setAuthBusy(true);setError("");try{if(authMode==="login"){const d=await signIn(email,password);setUserEmail(d.user?.email??email)}else{const d=await signUp(email,password,displayName);setUserEmail(d.user?.email??email);setAuthMode("login");setError(d.session?"":"Cadastro criado. Se a confirmação por e-mail estiver ativa, confirme o e-mail antes de entrar.")}await load()}catch(e:any){setError(e?.message||"Não foi possível concluir a autenticação.")}finally{setAuthBusy(false)}};
 const logout=async()=>{try{await signOut();setUserEmail(null);setMemberId(null);await load()}catch(e:any){setError(e?.message||"Não foi possível sair.")}};
 const toggleCamera=async()=>{const lk=livekitRoomRef.current;if(!lk)return;setVoiceBusy(true);try{await enableCamera(lk,!lk.localParticipant.isCameraEnabled)}catch(e:any){setVoiceError(e?.message||"Não foi possível alterar a câmera.")}finally{setVoiceBusy(false)}};
 const sendGift=async(g:any)=>{if(!room||!memberId||!g)return;setGiftBusy(true);try{if(!supabase){setWalletBalance(v=>Math.max(0,v-Number(g.virtual_cost_credits??0)));setGiftOpen(false);return}const target=seats.find(s=>s.member_id!==memberId)?.member_id??null;const result=await transferVirtualGift(room.id,memberId,target,g.id);setWalletBalance(Number(result.sender_balance));setGiftOpen(false)}catch(e:any){setError(e?.message||"Não foi possível enviar o presente.")}finally{setGiftBusy(false)}};

 return <div className="app"><header><div className="brand"><div className="logo">★</div><div><b>ESTRELA DA SORTE</b><span>VOICE • GAMES • ECOSSISTEMA</span></div></div><div className="status"><span className="dot"/>{livekitConfigured?(livekitState?.connected?"LIVEKIT • VOZ CONECTADA":"LIVEKIT CONFIGURADO"):"VOZ PENDENTE • LIVEKIT NÃO CONFIGURADO"}</div><div className="authBox">{supabaseConfigured?(userEmail?<><span>👤 {userEmail}</span><button onClick={()=>void logout()}>Sair</button></>:<><strong>{authMode==="login"?"Entrar":"Criar conta"}</strong>{authMode==="signup"&&<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Nome"/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha"/><button onClick={()=>void submitAuth()} disabled={authBusy}>{authBusy?"Aguarde…":authMode==="login"?"Entrar":"Cadastrar"}</button><button className="linkBtn" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"Criar conta":"Já tenho conta"}</button></>):<span>🧪 Modo teste local: sala, 30 cadeiras, chat e jogos podem ser testados sem backend.</span>}</div></header>
 <nav>{[["sala","Sala",Mic],["jogos","Jogos",Gamepad2],["agencia","Agência",Users],["admin","ADM",Shield]].map(([id,label,Icon]:any)=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon size={17}/>{label}</button>)}</nav>
 <main>{giftOpen&&<div className="modalBackdrop"><section className="modal"><div className="panelTitle"><span><Gift size={18}/> Presentes virtuais</span><small>Saldo {walletBalance}</small></div><div className="gamegrid">{(gifts.length?gifts:[{id:"demo1",name:"Estrela",gift_key:"DEMO_STAR",category:"sorte",virtual_cost_credits:100},{id:"demo2",name:"Lua",gift_key:"DEMO_MOON",category:"temático",virtual_cost_credits:250},{id:"demo3",name:"Supernova",gift_key:"DEMO_NOVA",category:"especial",virtual_cost_credits:500}]).map((g:any)=><button className="game" key={g.id} onClick={()=>void sendGift(g)} disabled={giftBusy||walletBalance<Number(g.virtual_cost_credits??0)}><div className="gameIcon">🎁</div><b>{g.name}</b><span>{g.virtual_cost_credits} créditos</span></button>)}</div><button onClick={()=>setGiftOpen(false)}>Fechar</button></section></div>} {tab==="sala"&&<section><section className="hero"><div><small>SALA AO VIVO</small><h1>{room?.title||"Sala principal"}</h1><p>{loading?"Consultando a sala real…":room?(room.seats+" posições configuradas • voz • vídeo opcional • chat • presentes"):"Nenhuma sala ao vivo encontrada"}</p></div><div className="actions"><button onClick={()=>void load()}><RefreshCw size={17}/> Atualizar</button><button onClick={()=>void toggleCamera()} disabled={!livekitState?.connected||voiceBusy}><Video size={17}/> {livekitState?.cameraEnabled?"Desligar vídeo":"Vídeo"}</button><button onClick={()=>setTab("sala")}><MessageCircle size={17}/> Chat</button><button className="gold" onClick={()=>setGiftOpen(true)} disabled={!memberId}><Gift size={17}/> Presentear</button></div></section>
 {error&&<div className="notice"><Settings size={17}/><span>{error}</span></div>}{voiceError&&<div className="notice"><Mic size={17}/><span>{voiceError}</span></div>}
 {!loading&&room&&<section className="panel"><div className="panelTitle"><span><Crown size={18}/> Cadeirinhas</span><small>{seats.length}/{room.seats} ocupadas • máximo técnico 30</small></div><div className="roomActions">{memberId?(mySeat?<><button onClick={()=>void toggleMic()} disabled={voiceBusy||!livekitState?.connected}><Mic size={16}/>{livekitState?.microphoneEnabled?"Desligar microfone":"Ligar microfone"}</button><button onClick={()=>void leave()} disabled={busy}><LogOut size={16}/> Sair da cadeira {mySeat}</button></>:<button onClick={()=>void join()} disabled={busy}><LogIn size={16}/> Entrar na sala</button>):<span>Login e membro ativo são necessários para ocupar uma cadeira.</span>}{voiceBusy&&<span>Conectando voz…</span>}</div><div className="seats">{Array.from({length:room.seats},(_,i)=>i+1).map(n=>{const s=occupied.get(n);return <div className={"seat "+(s?"live":"")} key={n}><div className="avatar">{s?"★":"+"}</div><b>{s?("Membro "+String(s.member_id).slice(0,6)):("Cadeira "+n)}</b><span>{s?"ao vivo":"livre"}</span></div>})}</div></section>}
 {room?.chat_enabled&&<section className="panel chatPanel"><div className="panelTitle"><span><MessageCircle size={18}/> Chat da sala</span><small>Realtime</small></div><div className="chatList">{chat.slice(-30).map(m=><div className="chatMsg" key={String(m.id)}><b>{String(m.sender_user_id).slice(0,8)}</b><span>{String(m.body)}</span></div>)}</div><div className="chatInput"><input value={message} maxLength={1000} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} placeholder={memberId?"Digite uma mensagem…":"Login necessário para enviar"}/><button onClick={()=>void send()} disabled={!memberId||!message.trim()}>Enviar</button></div></section>}</section>}
 {tab==="jogos"&&<GameCenter/>}
 {tab==="agencia"&&<section className="panel"><div className="panelTitle"><span><Users size={18}/> Agência & Hosts</span><small>estrutura preparada</small></div><div className="cards"><div className="card"><Star/><b>Agência</b><p>Equipe, convites, metas, resultados e hosts vinculados.</p></div><div className="card"><Mic/><b>Host</b><p>Entrada por convite, sala, metas e desempenho.</p></div><div className="card"><Crown/><b>BD</b><p>Acompanhamento de agências ativas e desempenho.</p></div></div></section>}
 {tab==="admin"&&<><section className="panel"><div className="panelTitle"><span><Shield size={18}/> Central ADM</span><small>controle por função</small></div><RoleHierarchy/><div className="notice"><Settings size={17}/><span>Permissões devem ser aplicadas no backend Supabase.</span></div></section><EventCalendar/></>}</main>
 <footer><span>Estrela da Sorte • Fundação 0.4</span><span>{supabaseConfigured?"Backend Supabase":"MODO TESTE LOCAL"} • Carteira: <b>{walletBalance} créditos</b></span></footer></div>}
export default App;