import React,{useEffect,useMemo,useState}from"react";
import RoleHierarchy from"./components/RoleHierarchy";
import{Gift,Gamepad2,Shield,Users,Settings,Mic,Video,MessageCircle,Star,Crown,ChevronRight,LogIn,LogOut,RefreshCw}from"lucide-react";
import{getLiveRoom,getCurrentMemberId,claimSeat,leaveSeat,listActiveSeats,RoomSession}from"./lib/room";
import{sendRoomMessage,subscribeToRoomChat}from"./lib/chat";
import{livekitConfigured}from"./lib/livekit";
import{supabase}from"./lib/supabase";

const games=["Caçador / John Hunter","Trem / Train","Mr. Rich","Crazy Cream","Feijão","Ovo","Aviador / Foguete","Yumi","Zeus","Cleópatra","Ice","Ludo","Uno","Estrela Cósmica","Órbita Dourada","Lua Violeta","Nebulosa","Supernova","Cometa","Galáxia"];

function App(){
 const[tab,setTab]=useState("sala"),[room,setRoom]=useState<RoomSession|null>(null),[seats,setSeats]=useState<any[]>([]),[memberId,setMemberId]=useState<string|null>(null),[chat,setChat]=useState<any[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const live=await getLiveRoom();setRoom(live);if(live){setSeats(await listActiveSeats(live.id));setMemberId(await getCurrentMemberId())}else{setSeats([]);setMemberId(null)}}catch(e:any){setError(e?.message||"Não foi possível consultar a sala.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!room||!supabase)return;return subscribeToRoomChat(room.id,m=>setChat(v=>[...v,m]))},[room]);
 const occupied=new Map(seats.map(s=>[Number(s.seat_no),s])),mySeat=useMemo(()=>seats.find(s=>s.member_id===memberId)?.seat_no??null,[seats,memberId]);
 const join=async()=>{if(!room||!memberId)return;setBusy(true);setError("");try{await claimSeat(room.id,memberId);await load()}catch(e:any){setError(e?.message||"Não foi possível ocupar a cadeira.")}finally{setBusy(false)}};
 const leave=async()=>{if(!room||!memberId)return;setBusy(true);setError("");try{await leaveSeat(room.id,memberId);await load()}catch(e:any){setError(e?.message||"Não foi possível sair da cadeira.")}finally{setBusy(false)}};
 const send=async()=>{if(!room||!message.trim())return;try{await sendRoomMessage(room.id,message.trim());setMessage("")}catch(e:any){setError(e?.message||"Não foi possível enviar a mensagem.")}};
 return <div className="app"><header><div className="brand"><div className="logo">★</div><div><b>ESTRELA DA SORTE</b><span>VOICE • GAMES • ECOSSISTEMA</span></div></div><div className="status"><span className="dot"/>{livekitConfigured?"ONLINE":"ONLINE • VOZ PENDENTE"}</div></header>
 <nav>{[["sala","Sala",Mic],["jogos","Jogos",Gamepad2],["agencia","Agência",Users],["admin","ADM",Shield]].map(([id,label,Icon]:any)=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon size={17}/>{label}</button>)}</nav>
 <main>{tab==="sala"&&<section><section className="hero"><div><small>SALA AO VIVO</small><h1>{room?.title||"Sala principal"}</h1><p>{loading?"Consultando a sala real…":room?\`${room.seats} posições configuradas • voz • vídeo opcional • chat • presentes\`:"Nenhuma sala ao vivo encontrada"}</p></div><div className="actions"><button onClick={()=>void load()}><RefreshCw size={17}/> Atualizar</button><button><Video size={17}/> Vídeo</button><button><MessageCircle size={17}/> Chat</button><button className="gold"><Gift size={17}/> Presentear</button></div></section>
 {error&&<div className="notice"><Settings size={17}/><span>{error}</span></div>}
 {!loading&&room&&<section className="panel"><div className="panelTitle"><span><Crown size={18}/> Cadeirinhas</span><small>{seats.length}/{room.seats} ocupadas • máximo técnico 30</small></div><div className="roomActions">{memberId?(mySeat?<button onClick={()=>void leave()} disabled={busy}><LogOut size={16}/> Sair da cadeira {mySeat}</button>:<button onClick={()=>void join()} disabled={busy}><LogIn size={16}/> Entrar na sala</button>):<span>Login e membro ativo são necessários para ocupar uma cadeira.</span>}</div><div className="seats">{Array.from({length:room.seats},(_,i)=>i+1).map(n=>{const s=occupied.get(n);return <div className={"seat "+(s?"live":"")} key={n}><div className="avatar">{s?"★":"+"}</div><b>{s?\`Membro ${String(s.member_id).slice(0,6)}\`:\`Cadeira ${n}\`}</b><span>{s?"ao vivo":"livre"}</span></div>})}</div></section>}
 {room?.chat_enabled&&<section className="panel chatPanel"><div className="panelTitle"><span><MessageCircle size={18}/> Chat da sala</span><small>Realtime</small></div><div className="chatList">{chat.slice(-30).map(m=><div className="chatMsg" key={String(m.id)}><b>{String(m.sender_user_id).slice(0,8)}</b><span>{String(m.body)}</span></div>)}</div><div className="chatInput"><input value={message} maxLength={1000} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} placeholder={memberId?"Digite uma mensagem…":"Login necessário para enviar"}/><button onClick={()=>void send()} disabled={!memberId||!message.trim()}>Enviar</button></div></section>}</section>}
 {tab==="jogos"&&<section className="panel"><div className="panelTitle"><span><Gamepad2 size={18}/> Jogos da sala</span><small>{games.length} registrados • 20 slots previstos</small></div><div className="gamegrid">{games.map((g,i)=><button className="game" key={g}><div className="gameIcon">{["♞","🚆","♛","🍦","🌱","🥚","🚀","🪐","⚡","👑","❄","🎲","🃏"][i]}</div><b>{g}</b><span>Entrar na sala <ChevronRight size={14}/></span></button>)}</div></section>}
 {tab==="agencia"&&<section className="panel"><div className="panelTitle"><span><Users size={18}/> Agência & Hosts</span><small>estrutura preparada</small></div><div className="cards"><div className="card"><Star/><b>Agência</b><p>Equipe, convites, metas, resultados e hosts vinculados.</p></div><div className="card"><Mic/><b>Host</b><p>Entrada por convite, sala, metas e desempenho.</p></div><div className="card"><Crown/><b>BD</b><p>Acompanhamento de agências ativas e desempenho.</p></div></div></section>}
 {tab==="admin"&&<section className="panel"><div className="panelTitle"><span><Shield size={18}/> Central ADM</span><small>controle por função</small></div><RoleHierarchy/><div className="notice"><Settings size={17}/><span>Permissões devem ser aplicadas no backend Supabase.</span></div></section>}</main>
 <footer><span>Estrela da Sorte • Fundação 0.4</span><span>Economia: <b>simulação controlada</b></span></footer></div>}
export default App;