-- V2.10 legacy migration retained for history.
-- The canonical reseller schema is defined in 0022_reseller_economy.sql.
-- This file is intentionally a no-op to avoid conflicting duplicate 0022 definitions.
